-- Recipe Reborn accesses these tables through server-side Prisma as postgres.
-- RLS is already enabled with no browser policies. Remove legacy Data API
-- privileges as defense in depth; do not add browser access or change RLS.
-- Timestamp generated by `supabase migration new`; kept in Prisma's layout.
BEGIN;

REVOKE ALL ON TABLE
    public."Account",
    public."Collection",
    public."CollectionRecipe",
    public."Folder",
    public."GuestUsage",
    public."MealPlan",
    public."MealPlanRecipe",
    public."Recipe",
    public."Session",
    public."ShoppingList",
    public."ShoppingListItem",
    public."User",
    public."VerificationToken",
    public."_prisma_migrations"
FROM anon, authenticated;

-- Prisma migrations create tables as postgres. Prevent the same legacy grants
-- on future postgres-owned public tables. Preserve postgres/service_role and
-- leave Supabase-managed roles' defaults and function/sequence ACLs untouched.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
    REVOKE ALL ON TABLES FROM anon, authenticated;

COMMIT;
